#!/usr/bin/env bash
# scripts/stage_completions.sh — converge completions owned by external taps
# and self-updating upstream CLIs after every provider has run.

GENERATED_COMPLETION_MARKER='# Generated by workspace-setup from the installed command; do not edit.'
GENERATED_COMPLETION_CONFLICTS=${GENERATED_COMPLETION_CONFLICTS:-0}

# The shell that will actually read these files. bash-completion@2 needs bash
# >= 4.2, so on macOS that is Homebrew's bash and never Apple's 3.2 — the same
# resolution postflight uses, so a file that passes here passes there.
completion_probe_bash() {
  if [[ -x "${BREW_PREFIX:-}/bin/bash" ]]; then
    printf '%s\n' "$BREW_PREFIX/bin/bash"
  else
    printf '%s\n' /bin/bash
  fi
}

# completion_ensure_dir <dir> — create <dir> and clear the group/other write
# bits zsh rejects. mkdir -p takes its mode from the caller's umask, so under
# umask 002 this setup would create a tree its own compaudit check then fails
# on. compaudit inspects an fpath directory and its immediate parent, which is
# exactly what is corrected here. A deliberately tighter mode such as 0700
# survives: only the write bits are removed.
completion_ensure_dir() {
  local dir="$1"
  mkdir -p "$dir"
  chmod go-w "$dir" "$(dirname "$dir")" 2>/dev/null || true
}

brew_completions_are_linked() {
  local state
  state=$("$BREW_BIN" completions state 2>/dev/null) || return 1
  [[ "$state" == *'are linked'* && "$state" != *'not linked'* ]]
}

ensure_brew_completions_linked() {
  [[ "${OS_KIND:-}" == macos && "${PKGMGR:-}" == brew ]] || return 0
  if brew_completions_are_linked; then
    ok "Homebrew external-command completions are linked"
    return 0
  fi

  info "linking completions supplied by installed Homebrew external commands…"
  "$BREW_BIN" completions link
  brew_completions_are_linked \
    || fail "brew completions link completed but Homebrew still reports them unlinked"
}

# completion_generate <command> <shell>
# Each command line below was verified against the installed publisher binary.
# OpenCode selects its output format from SHELL rather than from an argument.
completion_generate() {
  local command_name="$1" shell_name="$2"
  case "$command_name:$shell_name" in
    codex:bash) codex completion bash ;;
    codex:zsh) codex completion zsh ;;
    rustup:bash) rustup completions bash rustup ;;
    rustup:zsh) rustup completions zsh rustup ;;
    cargo:bash) rustup completions bash cargo ;;
    cargo:zsh) rustup completions zsh cargo ;;
    container:bash) container --generate-completion-script bash ;;
    container:zsh) container --generate-completion-script zsh ;;
    container-compose:bash) container-compose --generate-completion-script bash ;;
    container-compose:zsh) container-compose --generate-completion-script zsh ;;
    opencode:bash) SHELL=/bin/bash opencode completion ;;
    opencode:zsh) SHELL=/bin/zsh opencode completion ;;
    *) return 2 ;;
  esac
}

# Container Compose 0.5.x emits its executable's Swift target name,
# "application", rather than the installed command name. Change only the two
# registration lines; its internal _application function names are harmless.
completion_normalize_container_compose() {
  local shell_name="$1" src="$2" dst="$3"
  if [[ "$shell_name" == bash ]]; then
    sed 's/^complete -o filenames -F _application application$/complete -o filenames -F _application container-compose/' \
      "$src" > "$dst"
  else
    sed \
      -e 's/^#compdef application$/#compdef container-compose/' \
      -e 's/^    compdef _application application$/    compdef _application container-compose/' \
      "$src" > "$dst"
  fi
}

completion_is_setup_owned() {
  sed -n '1,3p' "$1" 2>/dev/null | grep -Fqx "$GENERATED_COMPLETION_MARKER"
}

completion_install_generated() {
  local command_name="$1" shell_name="$2" provider_command="$3" dst="$4"
  local tmp_dir raw normalized prepared first_line

  command -v "$provider_command" >/dev/null 2>&1 || return 0
  tmp_dir=$(mktemp -d "${TMPDIR:-/tmp}/workspace-completion.XXXXXX") || return 1
  raw="$tmp_dir/raw"
  normalized="$tmp_dir/normalized"
  prepared="$tmp_dir/prepared"

  if ! completion_generate "$command_name" "$shell_name" > "$raw" || [[ ! -s "$raw" ]]; then
    warn "$command_name produced no $shell_name completion"
    rm -rf "$tmp_dir"
    return 0
  fi

  if [[ "$command_name" == container-compose ]]; then
    completion_normalize_container_compose "$shell_name" "$raw" "$normalized"
  else
    cp "$raw" "$normalized"
  fi

  if [[ "$shell_name" == zsh ]]; then
    first_line=$(sed -n '1p' "$normalized")
    if [[ "$first_line" == '#compdef '* ]]; then
      {
        printf '%s\n%s\n' "$first_line" "$GENERATED_COMPLETION_MARKER"
        sed -n '2,$p' "$normalized"
      } > "$prepared"
    else
      {
        printf '#compdef %s\n%s\n' "$command_name" "$GENERATED_COMPLETION_MARKER"
        cat "$normalized"
      } > "$prepared"
    fi
    if ! /bin/zsh -n "$prepared" >/dev/null 2>&1; then
      warn "$command_name generated invalid zsh completion; preserving the current file"
      rm -rf "$tmp_dir"
      return 0
    fi
  else
    {
      printf '%s\n' "$GENERATED_COMPLETION_MARKER"
      cat "$normalized"
    } > "$prepared"
    if ! "$(completion_probe_bash)" -n "$prepared" >/dev/null 2>&1; then
      warn "$command_name generated invalid bash completion; preserving the current file"
      rm -rf "$tmp_dir"
      return 0
    fi
  fi

  if [[ -e "$dst" || -L "$dst" ]]; then
    if [[ ! -f "$dst" || -L "$dst" ]] || ! completion_is_setup_owned "$dst"; then
      GENERATED_COMPLETION_CONFLICTS=$((GENERATED_COMPLETION_CONFLICTS + 1))
      warn "preserving user-owned completion: $dst"
      rm -rf "$tmp_dir"
      return 0
    fi
    if cmp -s "$prepared" "$dst"; then
      rm -rf "$tmp_dir"
      return 0
    fi
  fi

  config_atomic_replace "$prepared" "$dst" 0644
  info "generated $shell_name completion for $command_name"
  rm -rf "$tmp_dir"
}

stage_completions() {
  [[ "${OS_KIND:-}" == macos ]] || return 0
  GENERATED_COMPLETION_CONFLICTS=0
  ensure_brew_completions_linked

  local bash_dir="$HOME/.local/share/bash-completion/completions"
  local zsh_dir="$HOME/.local/share/zsh/site-functions"
  completion_ensure_dir "$bash_dir"
  completion_ensure_dir "$zsh_dir"

  completion_install_generated codex bash codex "$bash_dir/codex"
  completion_install_generated rustup bash rustup "$bash_dir/rustup"
  completion_install_generated cargo bash rustup "$bash_dir/cargo"
  completion_install_generated opencode bash opencode "$bash_dir/opencode"

  completion_install_generated codex zsh codex "$zsh_dir/_codex"
  completion_install_generated rustup zsh rustup "$zsh_dir/_rustup"
  completion_install_generated cargo zsh rustup "$zsh_dir/_cargo"
  completion_install_generated opencode zsh opencode "$zsh_dir/_opencode"

  if [[ -z "${SKIP_CONTAINER:-}" ]]; then
    completion_install_generated container bash container "$bash_dir/container"
    completion_install_generated container-compose bash container-compose "$bash_dir/container-compose"
    completion_install_generated container zsh container "$zsh_dir/_container"
    completion_install_generated container-compose zsh container-compose "$zsh_dir/_container-compose"
  fi

  if ((GENERATED_COMPLETION_CONFLICTS)); then
    warn "$GENERATED_COMPLETION_CONFLICTS user-owned completion file(s) were left unchanged"
  else
    ok "generated completions are current"
  fi
}
